height: 500
menubar: false
plugins: 
  - image code advlist autolink lists link image charmap print preview anchor
  - searchreplace visualblocks code fullscreen
  - insertdatetime media table paste code help wordcount'
toolbar: undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help | code | image',
images_upload_url: /assets/images/tinymce_uploads
images_upload_credentials: true
block_formats: Paragraph=p; Heading 2=h2; Heading 3=h3; Heading 4=h4; Heading 5=h5; Heading 6=h6
